[project]
authors = ["Caroline Malin-Mayor <malinmayorc@janelia.hhmi.org>"]
channels = ["conda-forge"]
name = "funlib.geometry"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10,<3.14"

[pypi-dependencies]
"funlib.geometry" = { path = ".", editable = true}
